# Generated by Django 4.2.16 on 2024-09-04 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('recommended_direction', models.CharField(choices=[('sisters', 'Sisters'), ('it', 'IT')], default='sisters', max_length=10)),
                ('recommended_group', models.CharField(choices=[('junior', 'Младшая'), ('middle', 'Средняя'), ('senior', 'Старшая')], default='junior', max_length=10)),
                ('responsiveness', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1)),
                ('parents', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_back.group')),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('full_description', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name_description', to='crm_back.student')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_back.group')),
            ],
        ),
    ]
