# Generated by Django 4.2.16 on 2024-09-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='recommended_direction',
            field=models.CharField(choices=[('sisters', 'Sisters'), ('it', 'IT')], default='sisters', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='recommended_group',
            field=models.CharField(choices=[('junior', 'Младшая'), ('middle', 'Средняя'), ('senior', 'Старшая')], default='junior', max_length=10),
        ),
        migrations.AddField(
            model_name='student',
            name='responsiveness',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1),
        ),
    ]
