# Generated by Django 4.2.16 on 2024-09-05 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0002_alter_student_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='manager_description',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='parents',
            field=models.TextField(),
        ),
    ]
