# Generated by Django 4.2.16 on 2024-09-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_back', '0003_student_manager_description_alter_student_parents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='recommended_direction',
            field=models.CharField(blank=True, choices=[('sisters', 'Sisters'), ('it', 'IT'), ('not selected', 'Не выбрано')], default='Не выбрано', max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='recommended_group',
            field=models.CharField(blank=True, choices=[('junior', 'Младшая'), ('middle', 'Средняя'), ('senior', 'Старшая'), ('not selected', 'Не выбрано')], default='Не выбрано', max_length=12),
        ),
    ]
